# Generated by Django 3.1.7 on 2021-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='username',
        ),
        migrations.AlterField(
            model_name='link',
            name='long',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short',
            field=models.CharField(max_length=25),
        ),
    ]
